name: CI/CD for FastAPI Math App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest tests --maxfail=1 --disable-warnings -q

    - name: Simulate Deployment
      if: success()
      run: echo "🚀 All tests passed. FastAPI app is ready for deployment!"
