name: CI/CD Docker for FastAPI Math App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t math-ops:latest .

    - name: Run tests inside Docker
      run: |
        docker run --rm -e PYTHONPATH=/app math-ops:latest \
        python -m pytest tests --maxfail=1 --disable-warnings -q

    - name: Push Docker image to GHCR (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag math-ops:latest ghcr.io/${{ github.repository_owner }}/math-ops:latest
        docker push ghcr.io/${{ github.repository_owner }}/math-ops:latest
